baseurl: ""
url: "/"
markdown: kramdown
source: "src"
destination: "public"

collections:
  projects:
    output: true
  recognitions:
    output: true

gems:
  - octopress-paginate

exclude:
  - node_modules
